[package]
name = "notebooks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
glob = "0.3"

[dev-dependencies]
serial_test = "0.9"
tempdir = "0.3"
